name: Docker build
on:
  push:
    branches:
    - "master"
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build Docker
      run: |
        docker buildx build -t gilbertttsubay/docker-react:latest -f Dockerfile.dev .
    - name: Docker run test
      run: |
        docker run -e CI=true gilbertttsubay/docker-react:latest npm run test

