name: Docker build
on:
  push:
    branches:
    - "master"
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Build Docker Dockerfile.dev
      uses: actions/cache@v2
      with:
        path: ~/.docker/cache
        key: ${{ runner.os }}-docker-cache-dockerfiledev

    - name: Build Docker
      run: |
        docker buildx build -t gilbertttsubay/docker-react:latest -f Dockerfile.dev .
    - name: Docker run test
      run: |
        docker run -e CI=true gilbertttsubay/docker-react:latest npm run test

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: frontend
        environment_name: Frontend-env
        version_label: 1
        region: us-east-1
        deployment_package: deploy.zip

